% symbolic gradient of log(qlambda(x))
syms S1 S2 S3
muvecA=sym('muA',[1 NgaussA]);
muvecB=sym('muB',[1 NgaussB]);
muvecT=sym('muT',[1 NgaussT]);
sdvecA=sym('sdA',[1 NgaussA]);
sdvecB=sym('sdB',[1 NgaussB]);
sdvecT=sym('sdT',[1 NgaussT]);
wvecA=sym('wA',[1 NgaussA]);
wvecB=sym('wB',[1 NgaussB]);
wvecT=sym('wT',[1 NgaussT]);
assume([muvecA muvecB muvecT ...
        sdvecA sdvecB sdvecT ...
        wvecA  wvecB  wvecT ...
        S1     S2     S3],'real')

q=( log((  exp(-(S1-muvecA).^2/2./sdvecA.^2)./(sqrt(2*pi)*sdvecA)  )*wvecA') + ...
log((  exp(-(S2-muvecB).^2/2./sdvecB.^2)./(sqrt(2*pi)*sdvecB)  )*wvecB') + ...
log((  exp(-(S3-muvecT).^2/2./sdvecT.^2)./(sqrt(2*pi)*sdvecT)  )*wvecT') );

gradq=matlabFunction(gradient(q,[muvecA, sdvecA, wvecA, ...
            muvecB, sdvecB, wvecB, ...
            muvecT, sdvecT, wvecT])','Vars',[...
            muvecA muvecB muvecT ...
            sdvecA sdvecB sdvecT ...
            wvecA  wvecB  wvecT ...
            S1     S2     S3]);