p.Nmeas=8;
p.Nacro=16;
p.Nresidual=1e2;
p.Nperm=1e2;
p.freq=1;
p.Amp=1;
p.noise=.5;
p.Nbatch=10;
addpath('../utils_core')
[t,~]=getSamplingSchedules(p.Nmeas,0,0,0);
[X,I3,I4]=constructUtilMats(t,p);
tic
getPowerBatch(t,p,X,I3,I4);
toc